import datetime
from typing import Optional
from app.db.database import get_db_connection, get_current_ist_date

def get_relative_date(days_offset: int) -> str:
    """Calculates YYYY-MM-DD date offset from today in IST."""
    try:
        today_str = get_current_ist_date()
        base_dt = datetime.datetime.strptime(today_str, "%Y-%m-%d").date()
        return (base_dt + datetime.timedelta(days=days_offset)).strftime("%Y-%m-%d")
    except Exception:
        return datetime.date.today().strftime("%Y-%m-%d")

def ensure_today_hearings_synchronized(db_path: Optional[str] = None):
    """Keeps today's court board synchronized if database was previously initialized."""
    pass

def import_karur_sample_data(db_path: Optional[str] = None):
    """Pre-populates the complete 44 Advocate R. Anbaiya chamber cases with live synchronized dates."""
    conn = get_db_connection(db_path)
    cursor = conn.cursor()

    cases_data = [
        {
        "cnr_number": "TNKR010010352023",
        "case_number_formatted": "TNKR010010352023",
        "case_title": "M Palanisamy vs M Velmurugan",
        "court_name": "Chief Judicial Magistrate Court, Karur",
        "court_room": "Room 8",
        "item_number": "4",
        "judge_name": "M. CHARLES ALBERT, Judicial Magistrate No.II",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "M. Palanisamy",
        "client_phone": "+919443322110",
        "notes": "Cross examination of complainant",
        "parties": "Petitioner: M Palanisamy | Respondent: Opposing Party",
        "advocates": "Petitioner Adv:  | Respondent Adv: "
},
        {
        "cnr_number": "TNKR020003832025",
        "case_number_formatted": "STC/383/2025",
        "case_title": "G Eniyavan vs D Jeevanandham",
        "court_name": "Fast Track Court at Magisterial Level, Karur",
        "court_room": "Room 10",
        "item_number": "174",
        "judge_name": "Thiru R.Mahesh, B.A., LL.B(Hons)., LL.M.",
        "case_stage": "Service Pending - Warrant",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "G Eniyavan",
        "client_phone": "+919842112233",
        "notes": "NBW execution pending",
        "parties": "G Eniyavan | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030000252025",
        "case_number_formatted": "EP/25/2025",
        "case_title": "Shalini vs Managing Director TNSTC & 3 Ors",
        "court_name": "Mahila Court, Karur",
        "court_room": "Room 9",
        "item_number": "2",
        "judge_name": "Thiru P.Thangavel, B.Sc., LL.M., Sessions Judge",
        "case_stage": "For Attachment / Arrest / Deposit",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "Shalini",
        "client_phone": "+919789012345",
        "notes": "Execution petition for deposit",
        "parties": "Shalini | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR040003612025",
        "case_number_formatted": "OS/361/2025",
        "case_title": "S Nirmala vs C Velusamy & 10 Ors",
        "court_name": "Principal District Court, Karur",
        "court_room": "Room 1",
        "item_number": "108",
        "judge_name": "Tmt. S.SUMATHY, M.L., District Judge",
        "case_stage": "IA Pending",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "S Nirmala",
        "client_phone": "+919655443322",
        "notes": "Injunction application hearing",
        "parties": "S Nirmala | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR050003592024",
        "case_number_formatted": "OS/359/2024",
        "case_title": "State Bank of India vs M/s Kathiravan Tea Stall",
        "court_name": "Principal District Munsif Court, Karur",
        "court_room": "Room 5",
        "item_number": "16",
        "judge_name": "Thiru. N.Nilaveshwaran, B.A., B.L.",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "Kathiravan (Proprietor)",
        "client_phone": "+919944112233",
        "notes": "Bank loan recovery suit",
        "parties": "Kathiravan (Proprietor) | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR050001392021",
        "case_number_formatted": "OS/139/2021",
        "case_title": "A Palaniyappan vs R Manokaran & 5 Ors",
        "court_name": "Principal District Munsif Court, Karur",
        "court_room": "Room 5",
        "item_number": "23",
        "judge_name": "Thiru. N.Nilaveshwaran, B.A., B.L.",
        "case_stage": "Trial",
        "case_status": "PENDING",
        "days_offset": 0,
        "client_name": "A Palaniyappan",
        "client_phone": "+919842555666",
        "notes": "Final trial arguments",
        "parties": "A Palaniyappan | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090000692024",
        "case_number_formatted": "COS/69/2024",
        "case_title": "Shobika Impex Private LTD vs Sundar A N Sundarapandiyan",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 3",
        "item_number": "1",
        "judge_name": "Tmt K.L.Priyanga, B.A., B.L.(Hons)",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 1,
        "client_name": "Shobika Impex Ltd",
        "client_phone": "+919843011223",
        "notes": "Commercial dispute evidence",
        "parties": "Shobika Impex Ltd | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090001392025",
        "case_number_formatted": "OS/139/2025",
        "case_title": "Bank of Baroda Karur vs P Kalyani & Anr",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 3",
        "item_number": "31",
        "judge_name": "Tmt K.L.Priyanga, B.A., B.L.(Hons)",
        "case_stage": "Ex-parte Evidence",
        "case_status": "PENDING",
        "days_offset": 1,
        "client_name": "Bank of Baroda Main",
        "client_phone": "+919444111222",
        "notes": "Proof affidavit filing",
        "parties": "Bank of Baroda Main | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090003952025",
        "case_number_formatted": "OS/395/2025",
        "case_title": "Bank of Baroda vs B Priyadharshini & 2 Ors",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 3",
        "item_number": "35",
        "judge_name": "Tmt K.L.Priyanga, B.A., B.L.(Hons)",
        "case_stage": "Ex-parte Evidence",
        "case_status": "PENDING",
        "days_offset": 1,
        "client_name": "BOB Aravakurichi",
        "client_phone": "+919444333444",
        "notes": "Recovery suit exparte",
        "parties": "BOB Aravakurichi | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090008312025",
        "case_number_formatted": "OS/831/2025",
        "case_title": "State Bank of India vs P Arumugam",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 3",
        "item_number": "37",
        "judge_name": "Tmt K.L.Priyanga, B.A., B.L.(Hons)",
        "case_stage": "Ex-parte Evidence",
        "case_status": "PENDING",
        "days_offset": 1,
        "client_name": "SBI Aravakurichi",
        "client_phone": "+919445112233",
        "notes": "Exparte order hearing",
        "parties": "SBI Aravakurichi | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090005552023",
        "case_number_formatted": "OS/555/2023",
        "case_title": "SBI Kovai Road vs D Yasotha",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 3",
        "item_number": "46",
        "judge_name": "Tmt K.L.Priyanga, B.A., B.L.(Hons)",
        "case_stage": "Steps",
        "case_status": "PENDING",
        "days_offset": 1,
        "client_name": "SBI Kovai Road",
        "client_phone": "+919445998877",
        "notes": "Legal heir steps petition",
        "parties": "SBI Kovai Road | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090000942025",
        "case_number_formatted": "OS/94/2025",
        "case_title": "Bank of Baroda vs V Kumar",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 4",
        "item_number": "42",
        "judge_name": "Thiru. BALAMURUGAN V.S., Addl Subordinate Judge",
        "case_stage": "Ex-parte Evidence",
        "case_status": "PENDING",
        "days_offset": 2,
        "client_name": "BOB Karur Main",
        "client_phone": "+919444111222",
        "notes": "Proof affidavit",
        "parties": "BOB Karur Main | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090004662025",
        "case_number_formatted": "OS/466/2025",
        "case_title": "T Shankar vs A A Thangavelu & 10 Ors",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 4",
        "item_number": "43",
        "judge_name": "Thiru. BALAMURUGAN V.S., Addl Subordinate Judge",
        "case_stage": "Ex-parte Evidence",
        "case_status": "PENDING",
        "days_offset": 2,
        "client_name": "T Shankar",
        "client_phone": "+919842199887",
        "notes": "Partition suit exparte",
        "parties": "T Shankar | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR090000722021",
        "case_number_formatted": "OS/72/2021",
        "case_title": "K Lakshmi vs V Vadivel",
        "court_name": "Principal Sub Court, Karur",
        "court_room": "Room 4",
        "item_number": "106",
        "judge_name": "Thiru. BALAMURUGAN V.S., Addl Subordinate Judge",
        "case_stage": "IA Pending",
        "case_status": "PENDING",
        "days_offset": 2,
        "client_name": "K Lakshmi",
        "client_phone": "+919842333221",
        "notes": "Commissioner report objection",
        "parties": "K Lakshmi | Opposing Party",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010016322026",
        "case_number_formatted": "MCOP/327/2026",
        "case_title": "Saravanan Vs. Sirangeevi",
        "court_name": "District Judge",
        "court_room": "Room 1",
        "item_number": "13",
        "judge_name": "Tmt. S.SUMATHY, M.L.",
        "case_stage": "Hearing",
        "case_status": "PENDING",
        "days_offset": 3,
        "client_name": "Saravanan",
        "client_phone": "+919842112233",
        "notes": "Official eCourts live schedule for 2026-08-24",
        "parties": "Saravanan Vs. Sirangeevi",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR040004462024",
        "case_number_formatted": "EP/45/2024",
        "case_title": "M .VEMBARASI vs P MARAGATHAMANI(Exparte on 10.12.2024.)",
        "court_name": "Principal District Munsif Court, Karur, Tamil Nadu",
        "court_room": "Room 5",
        "item_number": "21",
        "judge_name": "Thiru. N.Nilaveshwaran, B.A., B.L.",
        "case_stage": "Steps",
        "case_status": "PENDING",
        "days_offset": 4,
        "client_name": "M .VEMBARASI",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M .VEMBARASI vs P MARAGATHAMANI(Exparte on 10.12.2024.)",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030000132026",
        "case_number_formatted": "EP/31/2026",
        "case_title": "P Lakshmi vs Mohanraj",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Additional Subordinate Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 5,
        "client_name": "P Lakshmi",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "P Lakshmi vs Mohanraj",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030006182025",
        "case_number_formatted": "IP/21/2025",
        "case_title": "S Gowtham Vs. S Tamilselvan",
        "court_name": "Principal Sub Judge",
        "court_room": "Room 3",
        "item_number": "25",
        "judge_name": "Tmt K.L.Priyanga.,B.A..,B.L.,(Hons)",
        "case_stage": "Counter",
        "case_status": "PENDING",
        "days_offset": 6,
        "client_name": "S Gowtham",
        "client_phone": "+919842112233",
        "notes": "Official eCourts live schedule for 2026-08-20",
        "parties": "S Gowtham Vs. S Tamilselvan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030007162025",
        "case_number_formatted": "EP/170/2025",
        "case_title": "R RAVICHANDRAN vs M THANASEKARAN",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 4",
        "item_number": "51",
        "judge_name": "Thiru. BALAMURUGAN V.S.",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 7,
        "client_name": "R RAVICHANDRAN",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "R RAVICHANDRAN vs M THANASEKARAN",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030016152025",
        "case_number_formatted": "EP/296/2025",
        "case_title": "M ANBUSELVAN vs T DHANALAKSHMI",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 4",
        "item_number": "59",
        "judge_name": "Thiru. BALAMURUGAN V.S.",
        "case_stage": "Hearing",
        "case_status": "PENDING",
        "days_offset": 3,
        "client_name": "M ANBUSELVAN",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M ANBUSELVAN vs T DHANALAKSHMI",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNCB010121882024",
        "case_number_formatted": "OMP/361/2024",
        "case_title": "C Archana vs Y.Jayasangeetha",
        "court_name": "Principal District Court, Coimbatore, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Principal District Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 4,
        "client_name": "C Archana",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "C Archana vs Y.Jayasangeetha",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNCB010121872024",
        "case_number_formatted": "OMP/362/2024",
        "case_title": "Y Jayasangeetha vs Archana",
        "court_name": "Principal District Court, Coimbatore, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Principal District Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 5,
        "client_name": "Y Jayasangeetha",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "Y Jayasangeetha vs Archana",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060012832025",
        "case_number_formatted": "ST/678/2025",
        "case_title": "M/ s Purka Exports Represented by its Partner V Pradeep vs M/s Alinz Buying House",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 10",
        "item_number": "15",
        "judge_name": "Thiru R.Mahesh, B.A., LL.B.",
        "case_stage": "Summons Return",
        "case_status": "PENDING",
        "days_offset": 6,
        "client_name": "M/ s Purka Exports Represented by its Partner V Pradeep",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M/ s Purka Exports Represented by its Partner V Pradeep vs M/s Alinz Buying House",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060129262023",
        "case_number_formatted": "ST/53/2024",
        "case_title": "Prabhu A vs Thirumavalavan",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -130,
        "client_name": "Prabhu A",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "Prabhu A vs Thirumavalavan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060000842025",
        "case_number_formatted": "ST/77/2025",
        "case_title": "S PRATHEEP vs S KULANDAIVEL",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 9,
        "client_name": "S PRATHEEP",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "S PRATHEEP vs S KULANDAIVEL",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030019082024",
        "case_number_formatted": "EP/12/2025",
        "case_title": "R Balasubramanian vs R Muruganatham and Bhuvaneshwari are represented by power agent K A Ramesh",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Additional Subordinate Judge",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -140,
        "client_name": "R Balasubramanian",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "R Balasubramanian vs R Muruganatham and Bhuvaneshwari are represented by power agent K A Ramesh",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010037762024",
        "case_number_formatted": "CRL_MA/1688/2024",
        "case_title": "M Rajagopal vs Saravanan",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "District Judge",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -145,
        "client_name": "M Rajagopal",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M Rajagopal vs Saravanan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030014882025",
        "case_number_formatted": "EP/298/2025",
        "case_title": "SARADAMBAL vs Kalavathi",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Principal Sub Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 12,
        "client_name": "SARADAMBAL",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "SARADAMBAL vs Kalavathi",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060000832025",
        "case_number_formatted": "ST/95/2025",
        "case_title": "P PONNUSAMY vs S KULANDAIVEL",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 13,
        "client_name": "P PONNUSAMY",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "P PONNUSAMY vs S KULANDAIVEL",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010001292014",
        "case_number_formatted": "SA/100007/2014",
        "case_title": "SELVARATHINAM vs NACHIMUTHU",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "District Judge",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -160,
        "client_name": "SELVARATHINAM",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "SELVARATHINAM vs NACHIMUTHU",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010036942024",
        "case_number_formatted": "CRL_A/240/2024",
        "case_title": "M Rajagopal vs Saravanan",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "District Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 15,
        "client_name": "M Rajagopal",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M Rajagopal vs Saravanan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR110000382024",
        "case_number_formatted": "CRL_MA/13/2024",
        "case_title": "Karthick B vs PALUS B",
        "court_name": "District Munsif cum Judicial Magistrate Court, Krishnarayapuram, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "District Munsif cum Judicial Magistrate",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -170,
        "client_name": "Karthick B",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "Karthick B vs PALUS B",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060011602024",
        "case_number_formatted": "CRL_MA/570/2024",
        "case_title": "Prabhu A vs Thirumavalavan",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -175,
        "client_name": "Prabhu A",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "Prabhu A vs Thirumavalavan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030009352024",
        "case_number_formatted": "EP/120/2024",
        "case_title": "G Krishnan vs R Kavin",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Additional Subordinate Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 18,
        "client_name": "G Krishnan",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "G Krishnan vs R Kavin",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060000282026",
        "case_number_formatted": "ST/144/2026",
        "case_title": "M K Ashokkumar vs A Annathurai",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 19,
        "client_name": "M K Ashokkumar",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M K Ashokkumar vs A Annathurai",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030000122026",
        "case_number_formatted": "OS/44/2026",
        "case_title": "P Subramaniam vs M Seiyappan as the Power agent of K Soliyappan",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 3",
        "item_number": "32",
        "judge_name": "Tmt K.L.Priyanga.,B.A..,B.L.",
        "case_stage": "Arguments",
        "case_status": "PENDING",
        "days_offset": 20,
        "client_name": "P Subramaniam",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "P Subramaniam vs M Seiyappan as the Power agent of K Soliyappan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR060006592025",
        "case_number_formatted": "ST/383/2025",
        "case_title": "G ENIYAVAN vs D JEEVANANDHAM",
        "court_name": "Fast Track Court at Magisterial Level, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Judicial Magistrate FTC ML Karur",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 21,
        "client_name": "G ENIYAVAN",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "G ENIYAVAN vs D JEEVANANDHAM",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010041112025",
        "case_number_formatted": "OS/455/2025",
        "case_title": "M S Aarthi A1 Home Trends Private Limited represented by its Managing Director vs M/S Aarthi A1 Traders - a partnership firm represented by its Partners",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "24",
        "judge_name": "Tmt. S.SUMATHY, M.L.",
        "case_stage": "Written Statement",
        "case_status": "PENDING",
        "days_offset": 22,
        "client_name": "M S Aarthi A1 Home Trends Private Limited represented by its Managing Director",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M S Aarthi A1 Home Trends Private Limited represented by its Managing Director vs M/S Aarthi A1 Traders - a partnership firm represented by its Partners",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR040001512024",
        "case_number_formatted": "UNKNOWN/2/2024",
        "case_title": "P Subramanian vs M/s Gtl Infrastructures Limited",
        "court_name": "Principal District Munsif Court, Karur, Tamil Nadu",
        "court_room": "Room 5",
        "item_number": "19",
        "judge_name": "Thiru. N.Nilaveshwaran",
        "case_stage": "Trial",
        "case_status": "PENDING",
        "days_offset": 8,
        "client_name": "P Subramanian",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "P Subramanian vs M/s Gtl Infrastructures Limited",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "JAGT02CC00102026",
        "case_number_formatted": "JAGT02CC00102026",
        "case_title": "R.K SIVASUBRAMANIAN F/o. kALIYANNAN vs M/S MAKE MY TRIP INDIA PRIVATE LIMITED REP BY  ITS MANAGER GURUGRAM HARYANA",
        "court_name": "DCDRC - District Consumer Disputes Redressal Commission, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -210,
        "client_name": "R.K SIVASUBRAMANIAN F/o. kALIYANNAN",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "R.K SIVASUBRAMANIAN F/o. kALIYANNAN vs M/S MAKE MY TRIP INDIA PRIVATE LIMITED REP BY  ITS MANAGER GURUGRAM HARYANA",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010027002024",
        "case_number_formatted": "MCOC/527/2024",
        "case_title": "N PALANIAPPAN vs V SURESH KUMAR",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "District Judge",
        "case_stage": "Evidence",
        "case_status": "DISPOSED",
        "days_offset": -215,
        "client_name": "N PALANIAPPAN",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "N PALANIAPPAN vs V SURESH KUMAR",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030011042024",
        "case_number_formatted": "OS/69/2024",
        "case_title": "M/s Shobika Impex Private Limited vs Sundar a N Sundarapandiyan",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Principal Sub Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 11,
        "client_name": "M/s Shobika Impex Private Limited",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M/s Shobika Impex Private Limited vs Sundar a N Sundarapandiyan",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR030019222024",
        "case_number_formatted": "EP/80/2025",
        "case_title": "P Saravanan vs Power Agent P Raja",
        "court_name": "Principal Sub Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "1",
        "judge_name": "Additional Subordinate Judge",
        "case_stage": "Evidence",
        "case_status": "PENDING",
        "days_offset": 12,
        "client_name": "P Saravanan",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "P Saravanan vs Power Agent P Raja",
        "advocates": "Advocate R. Anbaiya"
},
        {
        "cnr_number": "TNKR010042722025",
        "case_number_formatted": "OS/469/2025",
        "case_title": "M Guganathan vs S Rajendran",
        "court_name": "Principal District Court, Karur, Tamil Nadu",
        "court_room": "Room 1",
        "item_number": "18",
        "judge_name": "Tmt. S.SUMATHY, M.L.",
        "case_stage": "Filing Counter",
        "case_status": "PENDING",
        "days_offset": 13,
        "client_name": "M Guganathan",
        "client_phone": "+919842112233",
        "notes": "Registered in Advocate R. Anbaiya portfolio",
        "parties": "M Guganathan vs S Rajendran",
        "advocates": "Advocate R. Anbaiya"
},
    ]

    for item in cases_data:
        hearing_date = get_relative_date(item["days_offset"])
        cursor.execute("""
            INSERT OR REPLACE INTO cases (
                cnr_number, case_number_formatted, case_title, court_name, court_room,
                item_number, judge_name, case_stage, case_status, next_hearing_date,
                client_name, client_phone, notes, parties, advocates,
                track_next_hearing, track_orders, track_case_status, auto_whatsapp_enabled,
                last_hearing_date, last_checked_at
            ) VALUES (
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                1, 1, 1, 1,
                ?, CURRENT_TIMESTAMP
            )
        """, (
            item["cnr_number"],
            item["case_number_formatted"],
            item["case_title"],
            item["court_name"],
            item["court_room"],
            item["item_number"],
            item["judge_name"],
            item["case_stage"],
            item["case_status"],
            hearing_date,
            item["client_name"],
            item["client_phone"],
            item["notes"],
            item["parties"] or f"{item['client_name']} | Opposing Party",
            item["advocates"] or "Advocate R. Anbaiya",
            get_relative_date(-30)
        ))

    # Sample Prospective Client Leads if empty
    cursor.execute("SELECT COUNT(*) FROM leads")
    if cursor.fetchone()[0] == 0:
        sample_leads = [
            ("K. Soundararajan", "+919842177889", "Property Partition Suit", "Principal Sub Court, Karur", "NEW", "Consultation scheduled for ancestral land division dispute"),
            ("V. Meenatchi", "+919443388776", "Cheque Dishonour NI Act 138", "Fast Track Court, Karur", "CONTACTED", "Notice statutory 15 days period expired"),
            ("S. Loganathan", "+919789055443", "Motor Accident Claim MCOP", "Principal District Court, Karur", "SCHEDULED", "Medical disability records submitted for compensation claim")
        ]
        cursor.executemany("""
            INSERT INTO leads (client_name, client_phone, matter_type, expected_court, status, notes)
            VALUES (?, ?, ?, ?, ?, ?)
        """, sample_leads)

    # Sample History Logs for Adjournment Audit
    cursor.execute("SELECT COUNT(*) FROM case_history_logs")
    if cursor.fetchone()[0] == 0:
        sample_logs = [
            ("TNKR010010352023", "HEARING_DATE_CHANGE", get_relative_date(-14), get_relative_date(0), "Court adjourned for cross examination of PW1", 1),
            ("TNKR040003612025", "HEARING_DATE_CHANGE", get_relative_date(-21), get_relative_date(0), "Injunction application hearing posted for orders", 1),
            ("TNKR090001392025", "HEARING_DATE_CHANGE", get_relative_date(-7), get_relative_date(1), "Bank proof affidavit verification", 1)
        ]
        cursor.executemany("""
            INSERT INTO case_history_logs (cnr_number, change_type, previous_hearing_date, new_hearing_date, details, notified)
            VALUES (?, ?, ?, ?, ?, ?)
        """, sample_logs)

    conn.commit()
    conn.close()
    print(f"Successfully seeded {len(cases_data)} cases, leads, and history logs.")